// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSOADXKZcp2QWyemX8vfyWmcxfH_7WfxQ',
    appId: '1:512357649484:web:cbab64487f2785b167f8e9',
    messagingSenderId: '512357649484',
    projectId: 'portfolio-app-6c932',
    authDomain: 'portfolio-app-6c932.firebaseapp.com',
    storageBucket: 'portfolio-app-6c932.appspot.com',
    measurementId: 'G-WSPTXX534R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGugMna8YJwZlyXveEAyJHJ4766u28bOo',
    appId: '1:512357649484:android:a95008921004dbda67f8e9',
    messagingSenderId: '512357649484',
    projectId: 'portfolio-app-6c932',
    storageBucket: 'portfolio-app-6c932.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk3rH4jEUpbwxJ01Wk9HoL5QS3yNTCt8M',
    appId: '1:512357649484:ios:96e42d63d344f13a67f8e9',
    messagingSenderId: '512357649484',
    projectId: 'portfolio-app-6c932',
    storageBucket: 'portfolio-app-6c932.appspot.com',
    iosClientId: '512357649484-as30ogm4d03124jfko1nn20hks4ouj54.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk3rH4jEUpbwxJ01Wk9HoL5QS3yNTCt8M',
    appId: '1:512357649484:ios:96e42d63d344f13a67f8e9',
    messagingSenderId: '512357649484',
    projectId: 'portfolio-app-6c932',
    storageBucket: 'portfolio-app-6c932.appspot.com',
    iosClientId: '512357649484-as30ogm4d03124jfko1nn20hks4ouj54.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioApp',
  );
}
